apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-svc-deploy
  annotations: 
    kubernetes.io/change-cause: "version v1.0"
spec: 
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: books-service
  template: 
    metadata:
      labels:
        app: books-service
    spec: 
      containers:
        - image: shaikkhajaibrahim/libbookssvc:1.0
          name: books-service
          resources:  
            requests:
              memory: "24Mi"  
              cpu: "100m"  
            limits:
              memory: "128Mi" 
              cpu: "500m"  
          envFrom:
            - configMapRef:
                name: books-svc-deploy-config
          ports:
            - containerPort: 8000  

---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec: 
  type: ClusterIP
  selector:
    app: books-service  
  ports:
    - port: 8000
      targetPort: 8000