---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-webstore
  annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels: 
      app: webstore
  template:
    metadata: 
      labels: 
        app: webstore
    spec: 
      containers:
        - name: webstore
          image: shaikkhajaibrahim/libwebstore:1.0
          envFrom:
            - secretRef:
                name: webstore-secrets  # Reference to the secret containing environment variables
          resources:
            requests:
              memory: "24Mi"  
              cpu: "100m"     
            limits:
              memory: "128Mi" 
              cpu: "500m"     
          ports:
            - containerPort: 3000  # Port that the container listens on

---
apiVersion: v1
kind: Service
metadata:
  name: librarystore-svc
spec:
  type: LoadBalancer  # Exposes the service externally using a cloud provider's load balancer
  selector:
    app: webstore  # Selects pods with the label 'app=webstore'
  ports:
    - port: 80
      targetPort: 3000