---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: users-db-rs
  labels:
    app: users-db
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      db: users
  template:
    metadata: 
      labels: 
        db: users
    spec: 
      containers:
        - image: postgres:15-alpine
          name: usersdb
          envFrom:
          - configMapRef:
              name: users-db-config
          resources:
            requests:
              memory: "24Mi"  
              cpu: "100m"     
            limits:
              memory: "128Mi" 
              cpu: "500m"     
          ports:
            - containerPort: 5432 
---
apiVersion: v1
kind: Service
metadata:
  name: users-db-rs
spec:
  type: ClusterIP
  selector:
    db: users
  ports:
    - port: 5432
      targetPort: 5432