apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-svc-deploy
  annotations: 
    kubernetes.io/change-cause: "version v1.0"
spec: 
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template: 
    metadata:
      labels:
        app: users-service
    spec: 
      containers:
        - image: shaikkhajaibrahim/libuserssvc:1.0
          name: users-service
          resources:  
            requests:
              memory: "24Mi"  
              cpu: "100m"     
            limits:
              memory: "128Mi" 
              cpu: "500m"     
          envFrom:
            - configMapRef:
                name: users-svc-deploy-config
          ports:
            - containerPort: 8000  

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  selector:
    app: users-service  
  ports:
    - port: 8000
      targetPort: 8000