apiVersion: v1
kind: pod
metadata:
  name: activity5
  labels:
    env: dev
    app: web
    release: v1.6.9
spec:
  container:
    - name: test
      image: alpine
      args: 
      - sleep
        1d
      env:
        - name: USERNAME
          value: admin
        - name: PASSWORD
          value: admin@123
    
