---
apiVersion: v1
kind: Service
metadata:
  name: booksdb-svc
spec:
  type: ClusterIP
  clusterIP: None  
  selector:
    db: books
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booksdb
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      db: books
  serviceName: booksdb-svc
  template:
    metadata:
      labels:
        db: books
    spec:
      containers:
        - name: booksdb  
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: books-db-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"  
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: booksdb-vol
              mountPath: /var/lib/postgresql/data
              subPath: data  

  volumeClaimTemplates:  
    - metadata:
        name: booksdb-vol
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi