---
apiVersion: v1
kind: Service
metadata:
  name: usersdb-svc
spec:
  type: ClusterIP
  clusterIP: None  
  selector:
    db: users
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: usersdb
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      db: users
  serviceName: usersdb-svc
  template:
    metadata:
      labels:
        db: users
    spec:
      containers:
        - name: usersdb  
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: users-db-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"  
              cpu: "500m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: usersdb-vol
              mountPath: /var/lib/postgresql/data
              subPath: data  

  volumeClaimTemplates:  
    - metadata:
        name: usersdb-vol
      spec:
        accessModes:  
          - ReadWriteOnce
        storageClassName: managed
        resources:
          requests:
            storage: 1Gi