---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          resources:
            requests:
              memory: "24Mi"  
              cpu: "100m"
            limits:
              memory: "128Mi"  
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc  
spec:
  type: ClusterIP  
  selector:
    app: nginx  
  ports:
    - port: 80       
      targetPort: 80 