apiVersion: batch/v1
kind: CronJob
metadata:
  name: tx-cronjob
spec: 
  schedule: "* * * * *"
  jobTemplate:
    metadata: 
      labels: 
        app: tx-checker
    spec:
      template:
        metadata:
          labels:
            app: tx-checker
        spec:
          containers:
            - name: tx-checker
              image: alpine
              args: 
                - sleep
                - 1d   
          restartPolicy: OnFailure          
    