---
apiVersion: apps/v1
kind: ReplicaSet
metadate:
  name: spc-rs
  labels:
    app: spc
spec: 
  minReadySeconds: 1
  replicas: 2
  selector: 
    matchlabels: 
      app: spc
      env: Dev
    template: 
      metadata:
        labels: 
          app: spec
          env: Dev
          version: v1.6.9
      spec:
        name: spcapp
        image: shaikkhajaibrahim/spcjan2024:1.0
        resources:
          requests: 
            cpu: 250m
            memory: 256m
          limits:
            cpu: 500m
            memory: 256m
        ports:
          - containerPort: 8080
            protocol: TCP     

  
---
apiVersion: v1
kind: service
metadata: 
  name: spc-svc
  labels: 
    app: spc
spec:
  type: LoadBalancer
  selector:
    app: spc
    env: Dev
  ports:
    - port: 8080
      targetPort: 8080
