---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lib-webstore-rs
  labels:
    app: webstore
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      app: webstore
  template:
    metadata: 
      labels: 
        app: webstore
    spec: 
      containers:
        - image: shaikkhajaibrahim/libwebstore:1.0
          name: webstore
          env:
            - name: PREACT_APP_BACKEND_API_URL
              value: http://users-svc:8000/api/v1
            - name: PREACT_APP_BOOKS_API_URL
              value: http://books-svc:8000/api/v1/books
            - name: REACT_APP_USERS_API_URL
              value: http://users-svc:8000/api/v1/users
          resources:
            requests:
              memory: "24Mi"  
              cpu: "100m"     
            limits:
              memory: "128Mi" 
              cpu: "500m"     
          ports:
            - containerPort: 3000  