apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:9  
      resources:
        requests:
          memory: "256Mi"   
          cpu: "500m"
        limits:
          memory: "500Mi"  
          cpu: "1000m"
      ports:
        - containerPort: 3306
      envFrom:  
        - configMapRef:
            name: mysql-config
      volumeMounts:
        - name: libdb
          mountPath: /var/lib/mysql
  volumes: 
    - name: libdb
      persistentVolumeClaim: 
        claimName: mysql-pvc  