---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: skate-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1   
    kind: Deployment
    name: skate-deploy 
  metrics:
    - type: Resource      
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
