---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  namespace: qa
  annotations: 
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels: 
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers: 
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: "124Mi"
              cpu: "32m"
            limits:
              memory: "245Mi"
              cpu: "64m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: qa
spec:
  type: ClusterIP
  selector: 
    app: nginx1  
  ports: 
    - port: 80
      targetPort: 80  